apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service
data:
  AUTH_SERVICE_DATABASE_URL: "${AUTH_SERVICE_DATABASE_URL}"
  AUTH_SERVICE_DATABASE_USER: "${AUTH_SERVICE_DATABASE_USER}"
  AUTH_SERVICE_DATABASE_PASSWORD: "${AUTH_SERVICE_DATABASE_PASSWORD}"
  AUTH_SERVICE_DATABASE_NAME: "${AUTH_SERVICE_DATABASE_NAME}"
  AUTH_SERVICE_DATABASE_HOST: "mysql"
  AUTH_SERVICE_DATABASE_PORT: "3306"